stages:
  - check
check:
  stage: check
  tags:
    - nix
  script:
    - nix run github:lomenzel/nix --extra-experimental-features 'nix-command flakes pipe-operators' -- flake check --extra-experimental-features 'nix-command flakes pipe-operators'
